services:
  panel_app:
    container_name: panel_container
    build: .
    image: panel_app:v1
    ports:
      - "80:80"
    expose:
      - 80
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge