name: Panel Production Deploy (SSH Mode)
on:
  push:
    branches:
      - rezishon-patch-1
     
jobs:
  deploy:
    runs-on: local-host 
    steps:
      - name: Execute Remote Commands via SSH
        uses: https://github.com/appleboy/ssh-action@master
        with:
          host: 192.168.1.9  # Use your server's internal IP
          username: root
          key: ${{ secrets.PRIVATEKEYTOSSH }}
          port: 2280
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            nvm use 24

            cd /home/bpt-user/Downloads/Panel/
            git fetch origin main
            git reset --hard origin/main 
            
            if npm ci; then
              echo "Packages installed successfully"
            else
              echo "npm ci failed" && exit 1
            fi
            
            cp ../environment.ts ./src/environments/

            if ng build --output-hashing=all --configuration production; then
              echo "Build successful"
            else
              echo "Build failed" && exit 1
            fi

            if sudo nginx -s reload; then
              echo "Nginx reloaded successfully"
            else
              echo "Nginx reload failed" && exit 1
            fi
            