import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'سرویس ها',
      link: {
        type: 'generated-index',
        description: 'سرویس ها برای ارتباط با APIها مورد استفاده قرار میگیرند.',
      },
      items: [
        'services/captcha-service',
        'services/api-communication-management',
      ],
    },
    {
      type: 'category',
      label: 'مدل ها',
      link: {
        type: 'generated-index',
      },
      items: ['models/api-response'],
    },

    {
      type: 'category',
      label: 'کامپوننت های ورودی',
      link: {
        type: 'generated-index',
        description: 'کامپوننت های ورودی برای دریافت داده از کاربر.',
      },
      items: [
        'inputs/text-input-component',
        'inputs/search-input-component',
        'inputs/search-auto-complete-component',
        'inputs/search-auto-complete-factory',
        'inputs/password-input-component',
        'inputs/checkbox-input-component',
        'inputs/binary-radio-input-component',
        'inputs/toggle-switch-input-component',
        'inputs/date-picker-input-component',
        'inputs/time-picker-input-component',
        'inputs/captcha-input-component',
      ],
    },

    // The 'tutorial-basics' category
    // {
    //   type: 'category',
    //   label: 'Tutorial - Basics',
    //   // Docusaurus will look at _category_.json for label and position if 'link' is not specified
    //   // and autogenerate the index page if there is no index.md inside.
    //   items: [
    //     'tutorial-basics/create-a-document',
    //     'tutorial-basics/create-a-page',
    //     'tutorial-basics/create-a-blog-post',
    //     'tutorial-basics/markdown-features',
    //     'tutorial-basics/deploy-your-site',
    //     'tutorial-basics/congratulations',
    //   ],
    // },
    //
    // // The 'tutorial-extras' category
    // {
    //   type: 'category',
    //   label: 'Tutorial - Extras',
    //   // Docusaurus will autogenerate the index page if there is no index.md inside.
    //   items: [
    //     'tutorial-extras/manage-docs-versions',
    //     'tutorial-extras/translate-your-site',
    //   ],
    // },
  ],
   */
};

export default sidebars;
